name = "misub"
main = "functions/[[path]].js"
compatibility_date = "2024-06-13"

# 智能存储配置 - 根据可用性自动选择
# 如果您想只使用 D1，请注释掉 KV 配置
# 如果您想只使用 KV，请注释掉 D1 配置

# KV 命名空间绑定（可选）
# 如果您有可用的 KV 命名空间，请取消注释并填入正确的 ID
[[kv_namespaces]]
binding = "MISUB_KV"
id = "YOUR_KV_NAMESPACE_ID"  # 替换为您的真实 KV 命名空间 ID
preview_id = "YOUR_PREVIEW_KV_ID"  # 替换为您的预览 KV 命名空间 ID

# D1 数据库绑定（推荐）
# 如果您有可用的 D1 数据库，请取消注释并填入正确的 ID
[[d1_databases]]
binding = "MISUB_DB"
database_name = "misub"
database_id = "YOUR_D1_DATABASE_ID"  # 替换为您的真实 D1 数据库 ID
preview_database_id = "YOUR_D1_DATABASE_ID"  # 替换为您的真实 D1 数据库 ID

# 环境变量配置
[env.production.vars]
# 存储类型设置（可选）
# "auto" = 智能选择（推荐）
# "d1" = 强制使用 D1
# "kv" = 强制使用 KV
STORAGE_TYPE = "auto"

# 应用基础配置
ADMIN_PASSWORD = "admin"
COOKIE_SECRET = "a_very_long_random_secret_string"

# 定时任务配置
[triggers]
# 每6小时执行一次订阅更新
crons = ["0 */6 * * *"]

# 开发环境配置（可选）
[env.development]
# 开发环境可以使用不同的存储配置
[env.development.vars]
STORAGE_TYPE = "auto"
ADMIN_PASSWORD = "admin"
COOKIE_SECRET = "dev_secret_string"
